jp/deflation
JuliaApproximation/EquilibriumMeasures.jl pull request #5
Opened 2021-08-19 13:58 UTC by ioannisPApapadopoulos

Here are the necessary modifications to the Newton iteration in the `equilibriummeasure` function to utilize deflation when looking for multiple solutions of a one-interval log-kernel equilbrium measures problem. The Newton update is computed as normal and then (nonlinearly) scaled to prevent the Newton method converging to an already discovered solution. 

An example of a problem with 9 solutions (3 feasible) is found in `examples/non-unique-equilibrium-measure.jl`.

2021-08-19 17:42 UTC, TSGut commented
This is really cool! 

In terms of the terminology we've been using, are they all equilibrium measures? I think the global minimizer is called the equilibrium measure and the other potential local minimizers are just referred to as steady states and non uniqueness of steady states is not necessarily the same as non uniqueness of the equilibrium measures. We should maybe compute the energies along with the measured to check this.

2021-08-19 19:53 UTC, ioannisPApapadopoulos commented
great, thanks! in terms of the code, does that mean just computing the energies of all the 9 solutions in the example script? Is there anything else you had in mind?

2021-08-19 19:57 UTC, dlfivefifty commented
Yes, the energies should be greater than the equilibrium measure which has 3 intervals, and can currently only be computed in Mathematica 

you’ll need the log transform implemented to compute the energy, though point wise evaluation is fine and is easier to compute. Check out ` StieltjesPoint ` in stieltjes.jl for an example with the Cauchy/Stieltjes  kernel

2021-08-20 12:29 UTC, ioannisPApapadopoulos commented
Am I wrong in thinking that implementing the log transform for weighted U in this example can be done by simply re-implementing the already coded up log transform for weighted T (stieltjes.jl, lines 157-171)?

2021-08-20 13:51 UTC, dlfivefifty commented
https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/blob/94d58435970c692060351b68a81d08b41322ff74/src/stieltjes.jl#L157

is only for evaluating the log transform on the same interval. You can tell because `LogKernel{T,R,D}` where `R` is the type of the range interval and `D` is the type of the domain interval, in this case `R == D == ChebyshevInterval`, that is we know the domain and range are the same. 

 What we need for two-intervals is evaluating when `R` is a different interval. 

For comparison, for the Hilbert/Stieltjes case we have `R == D == ChebyshevInterval` here:

https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/blob/94d58435970c692060351b68a81d08b41322ff74/src/stieltjes.jl#L87

and `R ≠ D == ChebyshevInterval` here:

https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/blob/94d58435970c692060351b68a81d08b41322ff74/src/stieltjes.jl#L256

2021-08-20 14:03 UTC, ioannisPApapadopoulos commented
ok! and here we only want to perform the log transform over the range where the (feasible) measures are supported? So not on the whole domain (a,b)?

2021-08-20 14:46 UTC, ioannisPApapadopoulos commented
So should the following already be working? 

```
x = 0.1 # some real point, either on the domain or not
W = Weighted(ChebyshevU())
t = axes(W,1)
inv.(x .- t')' * W # should return a row-vector
```
I currently get a `DimensionMismatch` error.

`DimensionMismatch("Second axis of A, Base.OneTo(1), and first axis of B, Inclusion(-1.0..1.0 (Chebyshev)) must match")`

2021-08-20 15:01 UTC, dlfivefifty commented
You have an extra ` ‘ `

2021-08-20 15:02 UTC, dlfivefifty commented
because I did.. fixed my example

2021-08-20 15:04 UTC, ioannisPApapadopoulos commented
without the extra ', I am still getting an error:
```
MethodError: no method matching materialize!(::ArrayLayouts.MulAdd{ArrayLayouts.UnknownLayout, ArrayLayouts.UnknownLayout, LazyArrays.PaddedLayout{ArrayLayouts.DenseColumnMajor}, Float64, QuasiArrays.SubQuasiArray{Float64, 2, QuasiArrays.PermutedDimsQuasiArray{Float64, 2, (2, 1), (2, 1), Weighted{Float64, ChebyshevU{Float64}}}, Tuple{Base.Slice{InfiniteArrays.OneToInf{Int64}}, Inclusion{Float64, ChebyshevInterval{Float64}}}, false}, QuasiArrays.SubQuasiArray{Float64, 1, QuasiArrays.PermutedDimsQuasiArray{Float64, 2, (2, 1), (2, 1), QuasiArrays.BroadcastQuasiMatrix{Float64, typeof(inv), Tuple{QuasiArrays.BroadcastQuasiMatrix{Float64, typeof(-), Tuple{QuasiArrays.QuasiAdjoint{Float64, Inclusion{Float64, ChebyshevInterval{Float64}}}, Inclusion{Float64, ChebyshevInterval{Float64}}}}}}}, Tuple{Inclusion{Float64, ChebyshevInterval{Float64}}, Float64}, false}, LazyArrays.CachedArray{Float64, 1, Vector{Float64}, FillArrays.Zeros{Float64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}}})
Closest candidates are:
  materialize!(::Any, ::Base.Broadcast.Broadcasted{BS, Axes, F, Args} where {Axes, F, Args<:Tuple}) where {Style, BS<:BlockArrays.AbstractBlockStyle} at C:\Users\john.papad\.julia\packages\BlockArrays\rGDmR\src\blockbroadcast.jl:147
  materialize!(::Any, ::Base.Broadcast.Broadcasted{Style, Axes, F, Args} where {Axes, F, Args<:Tuple}) where Style at broadcast.jl:890
  materialize!(::Any, ::Any) at broadcast.jl:886
  ...
```

2021-08-20 20:46 UTC, dlfivefifty commented
Ah, for some reason it's only working for complex numbers right now:
```julia
julia> inv.(x .- t') * W
transpose((ComplexF64) .* ((ComplexF64) .^ ℵ₀-element InfiniteArrays.OneToInf{Int64} with indices OneToInf() with indices OneToInf()) with indices OneToInf()) with indices Base.OneTo(1)×OneToInf():
 0.0917376-1.29575im  -0.531751-0.0756742im  -0.0467394+0.21711im  …  
```
I'll have to look into that...

2021-08-21 00:08 UTC, dlfivefifty commented
Actually the issue isn't real or complex, it's that the code for evaluation when `t in ChebyshevInterval()` is broken. 

https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/pull/66

has a fix.

2021-08-21 15:32 UTC, ioannisPApapadopoulos commented
Thanks @dlfivefifty! Switching to the branch `dl/offhilbertcolsupportbug` did the trick and it works on my end now too! 

I suppose that implementing the evaluation of the energy at a point for the log-kernel would be part of a seperate PR for ClassicalOrthogonalPolynomials.jl. Would you want to merge this deflation PR into EquilibriumMeasures.jl or leave it as a branch for now?

2021-08-21 16:13 UTC, dlfivefifty commented
Let’s merge this, but perhaps it would be helpful to make it support other types like ` BigFloat ` . Do you want to have a try, or maybe at this point it is more helpful if I go through the code and make the necessary changes so you can learn what to do?

2021-08-21 18:41 UTC, ioannisPApapadopoulos commented
I am willing to give it a go! This would be my first time dealing with `BigFloat`, do you have a pointer to somewhere in JuliaApproximation where this has been done before? Maybe a commit where the necessary changes were made? (perhaps I am too optimistic here). Thank you!

2021-08-21 19:56 UTC, dlfivefifty commented
This is more basic Julia. Eg ` 0.0 ` vs ` zero(T) `.

some tricks are to use ` @code_warntype ` to decide whether the types are inferred (and so code is fast). For unit tests one uses ` @inferred `

2021-08-23 12:12 UTC, ioannisPApapadopoulos commented
Okay! So I think it's working in the sense that giving initial guesses that are `BigFloat` seems to work. Is there something more subtle that I may have missed?

2021-08-24 16:37 UTC, dlfivefifty requested changes

2021-08-24 16:37 UTC, dlfivefifty commented on src/EquilibriumMeasures.jl
> +function equilibriummeasure(V; a = SVector(-1.0,1.0), maxiterations=1000, knownsolutions=[], power=2, shift=1.0, dampening=1.0, returnEndpoint=false)
```suggestion
function equilibriummeasure(V; a = SVector(-1.0,1.0), maxiterations=1000, knownsolutions=[], power=2, shift=1.0, dampening=1.0, returnendpoint=false)
```
Julia convention is to only uses CamelCase for types. Sometimes `_` are used but tend to be skipped.

2021-08-24 16:37 UTC, dlfivefifty commented on src/EquilibriumMeasures.jl
> +    T = promote_type(typeof(state[1]), typeof(sol[1][1]))
```suggestion
    T = promote_type(eltype(state), eltype(eltype(sol)))
```

2021-08-24 16:37 UTC, dlfivefifty commented on src/EquilibriumMeasures.jl
> +    T = promote_type(typeof(state[1]), typeof(sol[1][1]))
```suggestion
    T = promote_type(eltype(state), eltype(eltype(sol)))
```

2021-08-24 16:37 UTC, dlfivefifty commented on src/EquilibriumMeasures.jl
> +        factor = one(T)/normsq^(0.5*power) + shift
```suggestion
        factor = one(T)/normsq^(power/2) + shift
```
`0.5` is a `Float64` so this version is more robust to other types.

2021-08-24 16:37 UTC, dlfivefifty commented on src/EquilibriumMeasures.jl
> +    T = promote_type(typeof(state[1]), typeof(sol[1][1]))
```suggestion
    T = promote_type(eltype(state), eltype(eltype(sol)))
```

2021-08-24 16:37 UTC, dlfivefifty commented on src/EquilibriumMeasures.jl
> +function  deflation_inner_products(state::SVector, sol)
Is there a reason to restrict to `SVector`? It seems the code would work for any `AbstractVector`

2021-08-24 16:37 UTC, dlfivefifty commented on src/EquilibriumMeasures.jl
> +        deriv = -power*state_dot_update/inner_products[iter]^(0.5*(power + 1))
```suggestion
        deriv = -power*state_dot_update/inner_products[iter]^((power + 1)/2)
```

2021-08-24 16:37 UTC, dlfivefifty commented on src/EquilibriumMeasures.jl
> +    T = promote_type(typeof(state[1]), typeof(sol[1][1]))
```suggestion
    T = promote_type(eltype(state), eltype(eltype(sol)))
```

2021-08-30 08:48 UTC, dlfivefifty approved these changes

2021-08-31 19:17 UTC, dlfivefifty commented
For the record: we need the following branch

https://github.com/JuliaDiff/ForwardDiff.jl/pull/541

I'll try to get this working with a custom Manifest.toml

2021-08-31 19:34 UTC, merged